# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install feedparser
    - name: Run Update Python Script
      run: |
        python3 main.py
    - name: Update README.md file
      run: | 
        git pull
        git add .
        git diff
        git config --local user.email "yangang4you@naver.com"
        git config --local user.name "busymidnight"
        git commit -m "Updating Blog Posts"
        git push
